### ISSUE TITLE
Deployment Issues for Server

### ISSUE THREAD

**Issue by KamalpreetSingh178** [KamalpreetSingh178/TripTales-Complete#7]
![image](https://github.com/KamalpreetSingh178/TripTales-Complete/assets/147826488/d63dcba5-a861-4a9f-a0c6-e379214df602)

**Comment by KamalpreetSingh178** [comment]
Resolved by updating build command in package.json
But new error has arised-
![image](https://github.com/KamalpreetSingh178/TripTales-Complete/assets/147826488/af5d362d-c2e3-49c8-adb5-72ae6c7d9f54)

**Comment by KamalpreetSingh178** [comment]
![image](https://github.com/KamalpreetSingh178/TripTales-Complete/assets/147826488/2ac4defc-9771-4fdd-bc15-1c5b7ac6e283)

**Comment by KamalpreetSingh178** [comment]
Nov 15 07:54:44 PM  ==> Deploying...
Nov 15 07:54:59 PM  ==> Using Node version 14.17.0 (default)
Nov 15 07:54:59 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 07:55:00 PM  ==> Running 'npm run dev'
Nov 15 07:55:01 PM  
Nov 15 07:55:01 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 07:55:01 PM  > nodemon index.js
Nov 15 07:55:01 PM  
Nov 15 07:55:01 PM  sh: 1: nodemon: not found
Nov 15 07:55:01 PM  npm ERR! code ELIFECYCLE
Nov 15 07:55:01 PM  npm ERR! syscall spawn
Nov 15 07:55:01 PM  npm ERR! file sh
Nov 15 07:55:01 PM  npm ERR! errno ENOENT
Nov 15 07:55:01 PM  npm ERR! server@1.0.0 dev: `nodemon index.js`
Nov 15 07:55:01 PM  npm ERR! spawn ENOENT
Nov 15 07:55:01 PM  npm ERR!
Nov 15 07:55:01 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 07:55:01 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 07:55:01 PM  
Nov 15 07:55:01 PM  npm ERR! A complete log of this run can be found in:
Nov 15 07:55:01 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T14_25_01_792Z-debug.log
Nov 15 07:55:06 PM  ==> Using Node version 14.17.0 (default)
Nov 15 07:55:06 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 07:55:06 PM  ==> Running 'npm run dev'
Nov 15 07:55:07 PM  
Nov 15 07:55:07 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 07:55:07 PM  > nodemon index.js
Nov 15 07:55:07 PM  
Nov 15 07:55:07 PM  sh: 1: nodemon: not found
Nov 15 07:55:07 PM  npm ERR! code ELIFECYCLE
Nov 15 07:55:07 PM  npm ERR! syscall spawn
Nov 15 07:55:07 PM  npm ERR! file sh
Nov 15 07:55:07 PM  npm ERR! errno ENOENT
Nov 15 07:55:07 PM  npm ERR! server@1.0.0 dev: `nodemon index.js`
Nov 15 07:55:07 PM  npm ERR! spawn ENOENT
Nov 15 07:55:07 PM  npm ERR!
Nov 15 07:55:07 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 07:55:07 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 07:55:07 PM  
Nov 15 07:55:07 PM  npm ERR! A complete log of this run can be found in:
Nov 15 07:55:07 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T14_25_07_895Z-debug.log
Nov 15 07:55:32 PM  ==> Using Node version 14.17.0 (default)
Nov 15 07:55:32 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 07:55:32 PM  ==> Running 'npm run dev'
Nov 15 07:55:34 PM  
Nov 15 07:55:34 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 07:55:34 PM  > nodemon index.js
Nov 15 07:55:34 PM  
Nov 15 07:55:34 PM  sh: 1: nodemon: not found
Nov 15 07:55:34 PM  npm ERR! code ELIFECYCLE
Nov 15 07:55:34 PM  npm ERR! syscall spawn
Nov 15 07:55:34 PM  npm ERR! file sh
Nov 15 07:55:34 PM  npm ERR! errno ENOENT
Nov 15 07:55:34 PM  npm ERR! server@1.0.0 dev: `nodemon index.js`
Nov 15 07:55:34 PM  npm ERR! spawn ENOENT
Nov 15 07:55:34 PM  npm ERR!
Nov 15 07:55:34 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 07:55:34 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 07:55:34 PM  
Nov 15 07:55:34 PM  npm ERR! A complete log of this run can be found in:
Nov 15 07:55:34 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T14_25_34_101Z-debug.log
Nov 15 07:55:59 PM  ==> Using Node version 14.17.0 (default)
Nov 15 07:55:59 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 07:55:59 PM  ==> Running 'npm run dev'
Nov 15 07:56:01 PM  
Nov 15 07:56:01 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 07:56:01 PM  > nodemon index.js
Nov 15 07:56:01 PM  
Nov 15 07:56:01 PM  sh: 1: nodemon: not found
Nov 15 07:56:01 PM  npm ERR! code ELIFECYCLE
Nov 15 07:56:01 PM  npm ERR! syscall spawn
Nov 15 07:56:01 PM  npm ERR! file sh
Nov 15 07:56:01 PM  npm ERR! errno ENOENT
Nov 15 07:56:01 PM  npm ERR! server@1.0.0 dev: `nodemon index.js`
Nov 15 07:56:01 PM  npm ERR! spawn ENOENT
Nov 15 07:56:01 PM  npm ERR!
Nov 15 07:56:01 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 07:56:01 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 07:56:01 PM  
Nov 15 07:56:01 PM  npm ERR! A complete log of this run can be found in:
Nov 15 07:56:01 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T14_26_01_195Z-debug.log
Nov 15 07:56:46 PM  ==> Using Node version 14.17.0 (default)
Nov 15 07:56:46 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 07:56:46 PM  ==> Running 'npm run dev'
Nov 15 07:56:47 PM  
Nov 15 07:56:47 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 07:56:47 PM  > nodemon index.js
Nov 15 07:56:47 PM  
Nov 15 07:56:48 PM  sh: 1: nodemon: not found
Nov 15 07:56:48 PM  npm ERR! code ELIFECYCLE
Nov 15 07:56:48 PM  npm ERR! syscall spawn
Nov 15 07:56:48 PM  npm ERR! file sh
Nov 15 07:56:48 PM  npm ERR! errno ENOENT
Nov 15 07:56:48 PM  npm ERR! server@1.0.0 dev: `nodemon index.js`
Nov 15 07:56:48 PM  npm ERR! spawn ENOENT
Nov 15 07:56:48 PM  npm ERR!
Nov 15 07:56:48 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 07:56:48 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 07:56:48 PM  
Nov 15 07:56:48 PM  npm ERR! A complete log of this run can be found in:
Nov 15 07:56:48 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T14_26_48_096Z-debug.log
Nov 15 07:58:24 PM  ==> Using Node version 14.17.0 (default)
Nov 15 07:58:24 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 07:58:24 PM  ==> Running 'npm run dev'
Nov 15 07:58:26 PM  
Nov 15 07:58:26 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 07:58:26 PM  > nodemon index.js
Nov 15 07:58:26 PM  
Nov 15 07:58:26 PM  sh: 1: nodemon: not found
Nov 15 07:58:26 PM  npm ERR! code ELIFECYCLE
Nov 15 07:58:26 PM  npm ERR! syscall spawn
Nov 15 07:58:26 PM  npm ERR! file sh
Nov 15 07:58:26 PM  npm ERR! errno ENOENT
Nov 15 07:58:26 PM  npm ERR! server@1.0.0 dev: `nodemon index.js`
Nov 15 07:58:26 PM  npm ERR! spawn ENOENT
Nov 15 07:58:26 PM  npm ERR!
Nov 15 07:58:26 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 07:58:26 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 07:58:26 PM  
Nov 15 07:58:26 PM  npm ERR! A complete log of this run can be found in:
Nov 15 07:58:26 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T14_28_26_101Z-debug.log
Nov 15 08:20:59 PM  ==> Using Node version 14.17.0 (default)
Nov 15 08:20:59 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 08:20:59 PM  ==> Running 'npm run dev'
Nov 15 08:21:01 PM  
Nov 15 08:21:01 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 08:21:01 PM  > nodemon index.js
Nov 15 08:21:01 PM  
Nov 15 08:21:01 PM  sh: 1: nodemon: not found
Nov 15 08:21:01 PM  npm ERR! code ELIFECYCLE
Nov 15 08:21:01 PM  npm ERR! syscall spawn
Nov 15 08:21:01 PM  npm ERR! file sh
Nov 15 08:21:01 PM  npm ERR! errno ENOENT
Nov 15 08:21:01 PM  npm ERR! server@1.0.0 dev: `nodemon index.js`
Nov 15 08:21:01 PM  npm ERR! spawn ENOENT
Nov 15 08:21:01 PM  npm ERR!
Nov 15 08:21:01 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 08:21:01 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 08:21:01 PM  
Nov 15 08:21:01 PM  npm ERR! A complete log of this run can be found in:
Nov 15 08:21:01 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T14_51_01_384Z-debug.log
Nov 15 08:21:06 PM  ==> Using Node version 14.17.0 (default)
Nov 15 08:21:06 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 08:21:06 PM  ==> Running 'npm run dev'
Nov 15 08:21:08 PM  
Nov 15 08:21:08 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 08:21:08 PM  > nodemon index.js
Nov 15 08:21:08 PM  
Nov 15 08:21:08 PM  sh: 1: nodemon: not found
Nov 15 08:21:08 PM  npm ERR! code ELIFECYCLE
Nov 15 08:21:08 PM  npm ERR! syscall spawn
Nov 15 08:21:08 PM  npm ERR! file sh
Nov 15 08:21:08 PM  npm ERR! errno ENOENT
Nov 15 08:21:08 PM  npm ERR! server@1.0.0 dev: `nodemon index.js`
Nov 15 08:21:08 PM  npm ERR! spawn ENOENT
Nov 15 08:21:08 PM  npm ERR!
Nov 15 08:21:08 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 08:21:08 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 08:21:08 PM  
Nov 15 08:21:08 PM  npm ERR! A complete log of this run can be found in:
Nov 15 08:21:08 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T14_51_08_296Z-debug.log
Nov 15 08:21:29 PM  ==> Using Node version 14.17.0 (default)
Nov 15 08:21:29 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 08:21:29 PM  ==> Running 'npm run dev'
Nov 15 08:21:31 PM  
Nov 15 08:21:31 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 08:21:31 PM  > nodemon index.js
Nov 15 08:21:31 PM  
Nov 15 08:21:31 PM  sh: 1: nodemon: not found
Nov 15 08:21:31 PM  npm ERR! code ELIFECYCLE
Nov 15 08:21:31 PM  npm ERR! syscall spawn
Nov 15 08:21:31 PM  npm ERR! file sh
Nov 15 08:21:31 PM  npm ERR! errno ENOENT
Nov 15 08:21:31 PM  npm ERR! server@1.0.0 dev: `nodemon index.js`
Nov 15 08:21:31 PM  npm ERR! spawn ENOENT
Nov 15 08:21:31 PM  npm ERR!
Nov 15 08:21:31 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 08:21:31 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 08:21:31 PM  
Nov 15 08:21:31 PM  npm ERR! A complete log of this run can be found in:
Nov 15 08:21:31 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T14_51_31_381Z-debug.log
Nov 15 08:22:12 PM  ==> Using Node version 14.17.0 (default)
Nov 15 08:22:12 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 08:22:12 PM  ==> Running 'npm run dev'
Nov 15 08:22:15 PM  
Nov 15 08:22:15 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 08:22:15 PM  > nodemon index.js
Nov 15 08:22:15 PM  
Nov 15 08:22:15 PM  sh: 1: nodemon: not found
Nov 15 08:22:15 PM  npm ERR! code ELIFECYCLE
Nov 15 08:22:15 PM  npm ERR! syscall spawn
Nov 15 08:22:15 PM  npm ERR! file sh
Nov 15 08:22:15 PM  npm ERR! errno ENOENT
Nov 15 08:22:15 PM  npm ERR! server@1.0.0 dev: `nodemon index.js`
Nov 15 08:22:15 PM  npm ERR! spawn ENOENT
Nov 15 08:22:15 PM  npm ERR!
Nov 15 08:22:15 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 08:22:15 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 08:22:15 PM  
Nov 15 08:22:15 PM  npm ERR! A complete log of this run can be found in:
Nov 15 08:22:15 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T14_52_15_281Z-debug.log
Nov 15 08:23:14 PM  ==> Using Node version 14.17.0 (default)
Nov 15 08:23:14 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 08:23:14 PM  ==> Running 'npm run dev'
Nov 15 08:23:15 PM  
Nov 15 08:23:15 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 08:23:15 PM  > nodemon index.js
Nov 15 08:23:15 PM  
Nov 15 08:23:15 PM  sh: 1: nodemon: not found
Nov 15 08:23:16 PM  npm ERR! code ELIFECYCLE
Nov 15 08:23:16 PM  npm ERR! syscall spawn
Nov 15 08:23:16 PM  npm ERR! file sh
Nov 15 08:23:16 PM  npm ERR! errno ENOENT
Nov 15 08:23:16 PM  npm ERR! server@1.0.0 dev: `nodemon index.js`
Nov 15 08:23:16 PM  npm ERR! spawn ENOENT
Nov 15 08:23:16 PM  npm ERR!
Nov 15 08:23:16 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 08:23:16 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 08:23:16 PM  
Nov 15 08:23:16 PM  npm ERR! A complete log of this run can be found in:
Nov 15 08:23:16 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T14_53_16_089Z-debug.log
Nov 15 08:42:25 PM  ==> Using Node version 14.17.0 (default)
Nov 15 08:42:25 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 08:42:25 PM  ==> Running 'npm run dev'
Nov 15 08:46:30 PM  ==> Using Node version 14.17.0 (default)
Nov 15 08:46:30 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 08:46:30 PM  ==> Running 'npm run dev'
Nov 15 08:46:34 PM  
Nov 15 08:46:34 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 08:46:34 PM  > nodemon index.js
Nov 15 08:46:34 PM  
Nov 15 08:46:34 PM  sh: 1: nodemon: not found
Nov 15 08:46:34 PM  npm ERR! code ELIFECYCLE
Nov 15 08:46:34 PM  npm ERR! syscall spawn
Nov 15 08:46:34 PM  npm ERR! file sh
Nov 15 08:46:34 PM  npm ERR! errno ENOENT
Nov 15 08:46:34 PM  npm ERR! server@1.0.0 dev: `nodemon index.js`
Nov 15 08:46:34 PM  npm ERR! spawn ENOENT
Nov 15 08:46:34 PM  npm ERR!
Nov 15 08:46:34 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 08:46:34 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 08:46:34 PM  
Nov 15 08:46:34 PM  npm ERR! A complete log of this run can be found in:
Nov 15 08:46:34 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T15_16_34_890Z-debug.log
Nov 15 08:59:20 PM  ==> Deploying...
Nov 15 09:01:06 PM  ==> Using Node version 14.17.0 (default)
Nov 15 09:01:06 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 09:01:06 PM  ==> Running 'npm run dev'
Nov 15 09:01:08 PM  
Nov 15 09:01:08 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 09:01:08 PM  > node index.js
Nov 15 09:01:08 PM  
Nov 15 09:01:11 PM  /opt/render/project/src/server/node_modules/bson/lib/bson.cjs:479
Nov 15 09:01:11 PM          inspect ??= defaultInspect;
Nov 15 09:01:11 PM                  ^^^
Nov 15 09:01:11 PM  
Nov 15 09:01:11 PM  SyntaxError: Unexpected token '??='
Nov 15 09:01:11 PM      at wrapSafe (internal/modules/cjs/loader.js:984:16)
Nov 15 09:01:11 PM      at Module._compile (internal/modules/cjs/loader.js:1032:27)
Nov 15 09:01:11 PM      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
Nov 15 09:01:11 PM      at Module.load (internal/modules/cjs/loader.js:933:32)
Nov 15 09:01:11 PM      at Function.Module._load (internal/modules/cjs/loader.js:774:14)
Nov 15 09:01:11 PM      at Module.require (internal/modules/cjs/loader.js:957:19)
Nov 15 09:01:11 PM      at require (internal/modules/cjs/helpers.js:88:18)
Nov 15 09:01:11 PM      at Object.<anonymous> (/opt/render/project/src/server/node_modules/mongodb/lib/bson.js:4:14)
Nov 15 09:01:11 PM      at Module._compile (internal/modules/cjs/loader.js:1068:30)
Nov 15 09:01:11 PM      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
Nov 15 09:01:11 PM  npm ERR! code ELIFECYCLE
Nov 15 09:01:11 PM  npm ERR! errno 1
Nov 15 09:01:11 PM  npm ERR! server@1.0.0 dev: `node index.js`
Nov 15 09:01:11 PM  npm ERR! Exit status 1
Nov 15 09:01:11 PM  npm ERR!
Nov 15 09:01:11 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 09:01:11 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 09:01:11 PM  
Nov 15 09:01:11 PM  npm ERR! A complete log of this run can be found in:
Nov 15 09:01:11 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T15_31_11_289Z-debug.log
Nov 15 09:02:34 PM  ==> Using Node version 14.17.0 (default)
Nov 15 09:02:34 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 09:02:34 PM  ==> Running 'npm run dev'
Nov 15 09:02:36 PM  
Nov 15 09:02:36 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 09:02:36 PM  > node index.js
Nov 15 09:02:36 PM  
Nov 15 09:02:38 PM  /opt/render/project/src/server/node_modules/bson/lib/bson.cjs:479
Nov 15 09:02:38 PM          inspect ??= defaultInspect;
Nov 15 09:02:38 PM                  ^^^
Nov 15 09:02:38 PM  
Nov 15 09:02:38 PM  SyntaxError: Unexpected token '??='
Nov 15 09:02:38 PM      at wrapSafe (internal/modules/cjs/loader.js:984:16)
Nov 15 09:02:38 PM      at Module._compile (internal/modules/cjs/loader.js:1032:27)
Nov 15 09:02:38 PM      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
Nov 15 09:02:38 PM      at Module.load (internal/modules/cjs/loader.js:933:32)
Nov 15 09:02:38 PM      at Function.Module._load (internal/modules/cjs/loader.js:774:14)
Nov 15 09:02:38 PM      at Module.require (internal/modules/cjs/loader.js:957:19)
Nov 15 09:02:38 PM      at require (internal/modules/cjs/helpers.js:88:18)
Nov 15 09:02:38 PM      at Object.<anonymous> (/opt/render/project/src/server/node_modules/mongodb/lib/bson.js:4:14)
Nov 15 09:02:38 PM      at Module._compile (internal/modules/cjs/loader.js:1068:30)
Nov 15 09:02:38 PM      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
Nov 15 09:02:38 PM  npm ERR! code ELIFECYCLE
Nov 15 09:02:38 PM  npm ERR! errno 1
Nov 15 09:02:38 PM  npm ERR! server@1.0.0 dev: `node index.js`
Nov 15 09:02:38 PM  npm ERR! Exit status 1
Nov 15 09:02:38 PM  npm ERR!
Nov 15 09:02:38 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 09:02:38 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 09:02:38 PM  
Nov 15 09:02:38 PM  npm ERR! A complete log of this run can be found in:
Nov 15 09:02:38 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T15_32_38_489Z-debug.log
Nov 15 09:03:01 PM  ==> Using Node version 14.17.0 (default)
Nov 15 09:03:01 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 15 09:03:01 PM  ==> Running 'npm run dev'
Nov 15 09:03:03 PM  
Nov 15 09:03:03 PM  > server@1.0.0 dev /opt/render/project/src/server
Nov 15 09:03:03 PM  > node index.js
Nov 15 09:03:03 PM  
Nov 15 09:03:05 PM  /opt/render/project/src/server/node_modules/bson/lib/bson.cjs:479
Nov 15 09:03:05 PM          inspect ??= defaultInspect;
Nov 15 09:03:05 PM                  ^^^
Nov 15 09:03:05 PM  
Nov 15 09:03:05 PM  SyntaxError: Unexpected token '??='
Nov 15 09:03:05 PM      at wrapSafe (internal/modules/cjs/loader.js:984:16)
Nov 15 09:03:05 PM      at Module._compile (internal/modules/cjs/loader.js:1032:27)
Nov 15 09:03:05 PM      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
Nov 15 09:03:05 PM      at Module.load (internal/modules/cjs/loader.js:933:32)
Nov 15 09:03:05 PM      at Function.Module._load (internal/modules/cjs/loader.js:774:14)
Nov 15 09:03:05 PM      at Module.require (internal/modules/cjs/loader.js:957:19)
Nov 15 09:03:05 PM      at require (internal/modules/cjs/helpers.js:88:18)
Nov 15 09:03:05 PM      at Object.<anonymous> (/opt/render/project/src/server/node_modules/mongodb/lib/bson.js:4:14)
Nov 15 09:03:05 PM      at Module._compile (internal/modules/cjs/loader.js:1068:30)
Nov 15 09:03:05 PM      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
Nov 15 09:03:05 PM  npm ERR! code ELIFECYCLE
Nov 15 09:03:05 PM  npm ERR! errno 1
Nov 15 09:03:05 PM  npm ERR! server@1.0.0 dev: `node index.js`
Nov 15 09:03:05 PM  npm ERR! Exit status 1
Nov 15 09:03:05 PM  npm ERR!
Nov 15 09:03:05 PM  npm ERR! Failed at the server@1.0.0 dev script.
Nov 15 09:03:05 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 15 09:03:05 PM  
Nov 15 09:03:05 PM  npm ERR! A complete log of this run can be found in:
Nov 15 09:03:05 PM  npm ERR!     /opt/render/.cache/_logs/2023-11-15T15_33_05_077Z-debug.log
